### ISSUE TITLE
Error with verbose argument

### ISSUE THREAD

**Issue by pdeschen** [jiaqi/jmxterm#15]
I get the following error while launching with the following arguments:

`java -jar jmxterm-1.0-alpha-4-uber.jar -l localhost:9010  -v`

```
java.lang.IllegalArgumentException: No enum constant org.cyclopsgroup.jmxterm.io.VerboseLevel.
	at java.lang.Enum.valueOf(Enum.java:238)
	at org.cyclopsgroup.jmxterm.io.VerboseLevel.valueOf(VerboseLevel.java:12)
	at org.cyclopsgroup.jmxterm.boot.CliMain.execute(CliMain.java:73)
	at org.cyclopsgroup.jmxterm.boot.CliMain.main(CliMain.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.classworlds.Launcher.launchStandard(Launcher.java:353)
	at org.codehaus.classworlds.Launcher.launch(Launcher.java:264)
	at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.classworlds.uberjar.boot.Bootstrapper.bootstrap(Bootstrapper.java:209)
	at org.codehaus.classworlds.uberjar.boot.Bootstrapper.main(Bootstrapper.java:116)
```

**Comment by jiaqi** [comment]
java -jar ..... -v verbose

**Comment by pdeschen** [comment]
Ah! `-v` flag is typically used by itself. I should have read the doc!
