### ISSUE TITLE
ERROR: bean name isn't valid

### ISSUE THREAD

**Issue by erolg** [jiaqi/jmxterm#22]
Hi there,
Im using jmxterm to monitor jmx mbeans of Solr.

When i set the domain like => "domain solr/song" then run beans command. It gives me all beans list.
Well. When i send request any attribute of any beans, i get it, bean name isn't valid. 

How could it be ? 

Example : 
$>domain solr/song
$>beans
#domain = solr/song:
solr/song:id=debug,type=debug
solr/song:id=facet,type=facet
solr/song:id=get,type=get
solr/song:id=highlight,type=highlight
solr/song:id=mlt,type=mlt
$>get -b solr/song:id=mlt,type=mlt *
#IllegalArgumentException: Bean name solr/song:id=mlt,type=mlt isn't valid.

**Comment by jiaqi** [comment]
Can you please run it with verbose output

run command "option -v verbose" before get command.

**Comment by codecounselor** [comment]
same problem for me
```
$>bean com.spider:instance=ROOT\ (4.0.2.18),name=asyncRunner
java.lang.IllegalArgumentException: Bean name com.spider:instance=ROOT isn't valid
	at org.cyclopsgroup.jmxterm.cmd.BeanCommand.getBeanName(BeanCommand.java:74)
	at org.cyclopsgroup.jmxterm.cmd.BeanCommand.execute(BeanCommand.java:122)
	at org.cyclopsgroup.jmxterm.cc.CommandCenter.doExecute(CommandCenter.java:161)
	at org.cyclopsgroup.jmxterm.cc.CommandCenter.doExecute(CommandCenter.java:134)
	at org.cyclopsgroup.jmxterm.cc.CommandCenter.execute(CommandCenter.java:176)
	at org.cyclopsgroup.jmxterm.boot.CliMain.execute(CliMain.java:149)
	at org.cyclopsgroup.jmxterm.boot.CliMain.main(CliMain.java:41)
```

**Comment by codecounselor** [comment]
Looks like someone else figured out two `\\` are needed https://github.com/jiaqi/jmxterm/issues/55#issuecomment-498332147
Seems like a great tool, would be superb if this just worked.
