### ISSUE TITLE
Support for JMX auth + SSL encryption

### ISSUE THREAD

**Issue by vroyer** [jiaqi/jmxterm#51]
Hi,

Even when adding the following SSL properties, jmxterm  over SSL+authentication failed (while it works in clear + authentication).  Does jmxterm support SSL and could you provide an example ?

-Djavax.net.ssl.trustStore=/etc/cassandra/truststore.jks
-Djavax.net.ssl.trustStorePassword=changeit 
-Dcom.sun.management.jmxremote.registry.ssl=true
-Dssl.enable=true

---------------------------------------------------
java.io.IOException: Failed to retrieve RMIServer stub: javax.naming.CommunicationException [Root exception is java.rmi.ConnectIOException: non-JRMP server at remote endpoint]
	at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:369)
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:270)
	at org.cyclopsgroup.jmxterm.cc.SessionImpl.doConnect(SessionImpl.java:85)
	at org.cyclopsgroup.jmxterm.cc.SessionImpl.connect(SessionImpl.java:49)
	at org.cyclopsgroup.jmxterm.cc.CommandCenter.connect(CommandCenter.java:110)
	at org.cyclopsgroup.jmxterm.boot.CliMain.execute(CliMain.java:139)
	at org.cyclopsgroup.jmxterm.boot.CliMain.main(CliMain.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.classworlds.Launcher.launchStandard(Launcher.java:353)
	at org.codehaus.classworlds.Launcher.launch(Launcher.java:264)
	at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.classworlds.uberjar.boot.Bootstrapper.bootstrap(Bootstrapper.java:209)
	at org.codehaus.classworlds.uberjar.boot.Bootstrapper.main(Bootstrapper.java:116)
Caused by: javax.naming.CommunicationException [Root exception is java.rmi.ConnectIOException: non-JRMP server at remote endpoint]
	at com.sun.jndi.rmi.registry.RegistryContext.lookup(RegistryContext.java:136)
	at com.sun.jndi.toolkit.url.GenericURLContext.lookup(GenericURLContext.java:205)
	at javax.naming.InitialContext.lookup(InitialContext.java:417)
	at javax.management.remote.rmi.RMIConnector.findRMIServerJNDI(RMIConnector.java:1955)
	at javax.management.remote.rmi.RMIConnector.findRMIServer(RMIConnector.java:1922)
	at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:287)
	... 20 more
Caused by: java.rmi.ConnectIOException: non-JRMP server at remote endpoint
	at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:248)
	at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:202)
	at sun.rmi.server.UnicastRef.newCall(UnicastRef.java:338)
	at sun.rmi.registry.RegistryImpl_Stub.lookup(RegistryImpl_Stub.java:112)
	at com.sun.jndi.rmi.registry.RegistryContext.lookup(RegistryContext.java:132)
	... 25 more

**Comment by jiaqi** [comment]
I don't believe this has been worked on. Please feel free to send pull request if you get it work.

**Comment by jluehe** [comment]
@jiaqi @vroyer, I just ran into the same issue and plan to provide a PR soon. Just wanted to give you guys a headsup.

**Comment by voiprodrigo** [comment]
Meanwhile, ghostunnel is a simple eorkaround ;)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by smiklosovic** [comment]
@jluehe any progress?

**Comment by smiklosovic** [comment]
I see it was implemented and merged but I am still getting `Root exception is java.rmi.ConnectIOException: non-JRMP server at remote endpoint`

**Comment by smiklosovic** [comment]
in case of JConsole I am able to connect like this:

`jconsole -J-Djavax.net.ssl.trustStore=/path/to/truststore.jks -J-Djavax.net.ssl.trustStorePassword=password`

After that I specify ip:port and username + password and I connect to server with ssl.

With jmxterm I am using same thing:

`java -Djavax.net.ssl.trustStore=/path/to/truststore.jks -Djavax.net.ssl.trustStorePassword=password -jar jmxterm-1.0.1-SNAPSHOT-uber.jar -l 172.19.0.5:7199 -u user -p password`

and I am still getting error as OP does.

**Comment by smiklosovic** [comment]
My bad, it works, I had to set "-s" and "-Dcom.sun.management.jmxremote.registry.ssl=true" on server side too

**Comment by jluehe** [comment]
Great, @smiklosovic! Thanks for confirming!

**Comment by jluehe** [comment]
@jiaqi, when do you plan to create a new release that would include this fix? Thx!

**Comment by jiaqi** [comment]
1.0.1 released. Thank you all for the support and help.

**Comment by jluehe** [comment]
Thank you, @jiaqi!

**Comment by abhijitdz** [comment]
I still get the same issue with 1.0.1 after enabling SSL ..

echo get -s -b java.lang:type=Memory HeapMemoryUsage | java -Djavax.net.ssl.trustStore=/path/trustustore.jks -Djavax.net.ssl.trustStorePassword=<password> -jar /somepath/jmxterm-1.0.1-uber.jar -l localhost:8099 -u <user> -p <password>
Feb 14, 2020 5:41:34 AM org.jline.utils.Log logr
WARNING: Unable to create a system terminal, creating a dumb terminal (enable debug logging for more information)
Exception in thread "main" java.io.IOException: Failed to retrieve RMIServer stub: javax.naming.CommunicationException [Root exception is java.rmi.ConnectIOException: non-JRMP server at remote endpoint]
	at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:369)

I can use jconsole fine .. (issuing command below, when console comes up, i pass in user and password) 

jconsole -J-Djavax.net.ssl.trustStore=/path/trustustore.jks  -J-Djavax.net.ssl.trustStorePassword=<password>


java -version
java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)

Both are set: 
CATALINA_OPTS="-Dcom.sun.management.jmxremote.registry.ssl=true $CATALINA_OPTS"
CATALINA_OPTS="-Dcom.sun.management.jmxremote.ssl=true ${CATALINA_OPTS}"

**Comment by abhijitdz** [comment]
> My bad, it works, I had to set "-s" and "-Dcom.sun.management.jmxremote.registry.ssl=true" on server side too

I have already set "-Dcom.sun.management.jmxremote.registry.ssl=true" on server side. What did you mean by "-s"
