### ISSUE TITLE
jmxterm does not work with OpenJDK11

### ISSUE THREAD

**Issue by dmandalidis** [jiaqi/jmxterm#69]
Switching in RHEL7 from :

`1.8.0.171-8.b10.el7_5`

to 

`11.0.1.13-3.el7_6` or `11.0.4.11-1.el7_7`.

The following command:
```
java -jar /opt/applications/monitoring/jmxterm-1.0.0-uber.jar -l ${KAFKA_HOST}:9999 -n < /opt/applications/monitoring/jmx-config
```

throws the following exception:

```
java.lang.NullPointerException
	at org.codehaus.classworlds.Launcher.getEnhancedMainMethod(Launcher.java:195)
	at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:294)
	at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
	at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.classworlds.uberjar.boot.Bootstrapper.bootstrap(Bootstrapper.java:209)
	at org.codehaus.classworlds.uberjar.boot.Bootstrapper.main(Bootstrapper.java:116)
```

My gut feeling that it generally doesn't work with OpenJDK11 independently of the exact version

(_edit_: format exception)

**Comment by dmandalidis** [comment]
Sorry, false alarm; this was the behaviour with 1.0.0, with 1.0.1 everything is fine.
