### ISSUE TITLE
jxmterm Will Not Run on JDK11 (amazon corretto)

### ISSUE THREAD

**Issue by ppridge** [jiaqi/jmxterm#71]
$ java -version
openjdk version "11.0.5" 2019-10-15 LTS
OpenJDK Runtime Environment Corretto-11.0.5.10.1 (build 11.0.5+10-LTS)
OpenJDK 64-Bit Server VM Corretto-11.0.5.10.1 (build 11.0.5+10-LTS, mixed mode)

$ java -jar jmxterm-1.0.0-uber.jar
java.lang.NullPointerException
        at org.codehaus.classworlds.Launcher.getEnhancedMainMethod(Launcher.java:195)
        at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:294)
        at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
        at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
        at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.classworlds.uberjar.boot.Bootstrapper.bootstrap(Bootstrapper.java:209)
        at org.codehaus.classworlds.uberjar.boot.Bootstrapper.main(Bootstrapper.java:116)

**Comment by progulin** [comment]
Exactly the same:
`/opt/jmxterm-1.0.0$ /usr/lib/jvm/java-1.11.0-openjdk-amd64/bin/java -jar /opt/jmxterm-1.0.0/jmxterm-1.0.0-uber.jar 
java.lang.NullPointerException                                                                                     
        at org.codehaus.classworlds.Launcher.getEnhancedMainMethod(Launcher.java:195)                              
        at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:294)                                     
        at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)                                             
        at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)                                   
        at org.codehaus.classworlds.Launcher.main(Launcher.java:375)                                               
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)                          
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)        
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)                                              
        at org.codehaus.classworlds.uberjar.boot.Bootstrapper.bootstrap(Bootstrapper.java:209)                     
        at org.codehaus.classworlds.uberjar.boot.Bootstrapper.main(Bootstrapper.java:116)                          `

JDK version:
`/usr/lib/jvm/java-1.11.0-openjdk-amd64/bin$ /usr/lib/jvm/java-1.11.0-openjdk-amd64/bin/java -version
openjdk version "11.0.4" 2019-07-16                                                                 
OpenJDK Runtime Environment (build 11.0.4+11-post-Ubuntu-1ubuntu218.04.3)                           
OpenJDK 64-Bit Server VM (build 11.0.4+11-post-Ubuntu-1ubuntu218.04.3, mixed mode, sharing)         `

**Comment by alexandrpaliy** [comment]
Unfortunately, same here.

**Comment by alexandrpaliy** [comment]
But, actually, it works fine with latest jmxterm version - 1.0.1
Credits to https://github.com/jiaqi/jmxterm/issues/67

**Comment by TheCycoONE** [comment]
So this can be closed right - I use 1.0.2 with corretto.

**Comment by nyg** [comment]
Just for the record, I think that the PR that fixed this was #59, not #67… :)
