### ISSUE TITLE
not working inside a container of `mcr.microsoft.com/java/jre-headless:11-zulu-centos` image

### ISSUE THREAD

**Issue by yasserzamani** [jiaqi/jmxterm#91]
As already mentioned by others, looks like not working with headless jre, is it known and expected? Or it's going and is possible to be fixed?
```
98s         Warning   Unhealthy   pod/xxxxxx-7d5588cf66-ss9xp   Liveness probe failed: Exception in thread "main" j
ava.lang.UnsupportedOperationException: sun.tools.jconsole.LocalVirtualMachine, operation on this JDK(11.0.9.1+1-LTS) is
n't fully supported
            at org.cyclopsgroup.jmxterm.pm.UnsupportedJavaProcessManager.get(UnsupportedJavaProcessManager.java:40)
            at org.cyclopsgroup.jmxterm.SyntaxUtils.getUrl(SyntaxUtils.java:41)
            at org.cyclopsgroup.jmxterm.boot.CliMain.execute(CliMain.java:135)
            at org.cyclopsgroup.jmxterm.boot.CliMain.main(CliMain.java:41)
Caused by: java.lang.ClassNotFoundException: sun.tools.jconsole.LocalVirtualMachine
            at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
            at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
            at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
            at org.cyclopsgroup.jmxterm.jdk6.Jdk6JavaProcessManager.<init>(Jdk6JavaProcessManager.java:22)
            at org.cyclopsgroup.jmxterm.cc.JPMFactory.<init>(JPMFactory.java:33)
            at org.cyclopsgroup.jmxterm.cc.CommandCenter.<init>(CommandCenter.java:75)
            at org.cyclopsgroup.jmxterm.cc.CommandCenter.<init>(CommandCenter.java:60)
            at org.cyclopsgroup.jmxterm.boot.CliMain.execute(CliMain.java:113)
            ... 1 more
```

**Comment by jiaqi** [comment]
I never tested on JDK 11. Seems a class jmxterm relies on, LocalVirtualMachine, no longer exists.

**Comment by yasserzamani** [comment]
No it's not JDK but `headless jre` 11. Yes it doesn't have it owing to because it's headless I think. The question is: Is it known and expected? Or it's going and is possible to be fixed?

**Comment by jiaqi** [comment]
I didn't realize it's JRE. No it doesn't work with JRE, it relies on some library in JDK. Specifically, the jconsole.jar if I remember it right.
